# Generated by Django 5.2.3 on 2025-06-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sisa_cuti_melahirkan',
            field=models.PositiveIntegerField(default=90, verbose_name='Sisa Cuti Melahirkan (Hari)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sisa_cuti_sakit',
            field=models.PositiveIntegerField(default=14, verbose_name='Sisa Cuti Sakit (Hari)'),
        ),
    ]
