# Generated by Django 5.2.3 on 2025-06-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_sisa_cuti_melahirkan_profile_sisa_cuti_sakit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sisa_cuti_alasan_penting',
            field=models.PositiveIntegerField(default=7, verbose_name='Sisa Cuti Alasan Penting (Hari)'),
        ),
    ]
