# Generated by Django 5.2.3 on 2025-06-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_sisa_cuti_alasan_penting'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_kepegawaian',
            field=models.CharField(choices=[('PNS', 'PNS'), ('PPPK', 'PPPK')], default='PNS', max_length=4, verbose_name='Status Kepegawaian'),
        ),
    ]
