# Generated by Django 5.2.3 on 2025-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_status_kepegawaian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Pengguna', 'verbose_name_plural': 'Daftar Pengguna'},
        ),
        migrations.AddField(
            model_name='user',
            name='wajib_ganti_password',
            field=models.BooleanField(default=True),
        ),
    ]
