# Generated by Django 5.2.3 on 2025-07-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_user_wajib_ganti_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wajib_ganti_password',
        ),
    ]
