# Generated by Django 5.2.3 on 2025-06-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Daftar Jenis Cuti',
            },
        ),
        migrations.CreateModel(
            name='PengajuanCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alasan', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('lama_cuti', models.PositiveIntegerField(help_text='Jumlah hari kerja')),
                ('alamat_selama_cuti', models.TextField()),
                ('telepon_selama_cuti', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ATASAN', 'Menunggu Persetujuan Atasan'), ('PENDING_KEPALA', 'Menunggu Keputusan Kepala'), ('DISETUJUI', 'Disetujui'), ('DITOLAK_ATASAN', 'Ditolak oleh Atasan'), ('DITOLAK_KEPALA', 'Ditolak oleh Kepala'), ('PERUBAHAN', 'Disarankan Perubahan'), ('DITANGGUHKAN', 'Ditangguhkan')], default='PENDING_ATASAN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catatan_atasan', models.TextField(blank=True, null=True)),
                ('tanggal_pertimbangan_atasan', models.DateTimeField(blank=True, null=True)),
                ('catatan_kepala', models.TextField(blank=True, null=True)),
                ('tanggal_keputusan_kepala', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Pengajuan Cuti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaldoCutiTahunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField()),
                ('sisa_hari', models.PositiveIntegerField(default=12)),
            ],
            options={
                'verbose_name_plural': 'Data Saldo Cuti Tahunan',
            },
        ),
    ]
