# Generated by Django 5.2.3 on 2025-06-19 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuancuti',
            name='atasan_penyetuju',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persetujuan_atasan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengajuancuti',
            name='jenis_cuti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuti.jeniscuti'),
        ),
        migrations.AddField(
            model_name='pengajuancuti',
            name='kepala_penyetuju',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persetujuan_kepala', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengajuancuti',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saldocutitahunan',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_cuti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='saldocutitahunan',
            unique_together={('pegawai', 'tahun')},
        ),
    ]
