# Generated by Django 5.2.3 on 2025-06-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HariLibur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True)),
                ('keterangan', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Daftar Hari Libur',
                'ordering': ['tanggal'],
            },
        ),
    ]
