# Generated by Django 5.2.3 on 2025-06-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0003_harilibur'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeniscuti',
            name='berlaku_untuk',
            field=models.CharField(choices=[('SEMUA', 'Semua (PNS & PPPK)'), ('PNS', 'Hanya PNS'), ('PPPK', 'Hanya PPPK')], default='SEMUA', max_length=5, verbose_name='Berlaku Untuk'),
        ),
    ]
