# Generated by Django 5.2.3 on 2025-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0004_jeniscuti_berlaku_untuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuancuti',
            name='dokumen_pendukung',
            field=models.FileField(blank=True, null=True, upload_to='dokumen_cuti/', verbose_name='Dokumen Pendukung (jika ada)'),
        ),
    ]
