# Generated by Django 5.2.3 on 2025-06-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0005_pengajuancuti_dokumen_pendukung'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuancuti',
            name='tanda_tangan_pegawai',
            field=models.TextField(blank=True, null=True, verbose_name='Tanda Tangan Pegawai (Data URL)'),
        ),
    ]
